2019-12-10 11:35:33,146 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:12: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-12-10 11:35:33,146 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-12-10 11:35:33,566 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:18: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-12-10 11:35:33,571 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:19: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

2019-12-10 11:35:33,584 WARNING tensorflow From main_train_and_test_adam_opt.py:101: The name tf.make_template is deprecated. Please use tf.compat.v1.make_template instead.

2019-12-10 11:35:33,587 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/data_generator.py:22: The name tf.FIFOQueue is deprecated. Please use tf.queue.FIFOQueue instead.

2019-12-10 11:35:33,594 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-12-10 11:35:33,594 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/SegCaps.py:27: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
2019-12-10 11:35:33,689 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3714194d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3714194d68>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:33,818 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37140f35f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37140f35f8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:33,895 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37140f35f8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37140f35f8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:33,920 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3714194b70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3714194b70>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:33,985 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:359: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-10 11:35:33,993 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:389: calling norm (from tensorflow.python.ops.linalg_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-12-10 11:35:34,099 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37140fb128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37140fb128>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:34,175 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37140fb128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37140fb128>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:34,193 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:34,353 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3704786160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3704786160>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:34,428 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3704786080>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3704786080>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:34,447 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:34,608 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37046da278>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37046da278>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:34,682 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37046da320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37046da320>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:34,701 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:34,861 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37046e9908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37046e9908>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:34,934 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37046e9ba8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37046e9ba8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:34,953 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:35,114 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37045785c0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37045785c0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:35,189 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37047e28d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37047e28d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:35,207 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:35,368 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f370448ee10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f370448ee10>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:35,442 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f370448ee10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f370448ee10>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:35,467 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f373736b0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f373736b0b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:35,643 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f370438a518>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f370438a518>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:35,717 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37043f2b00>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37043f2b00>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:35,735 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:36,000 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3704287198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3704287198>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:36,074 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3704287780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f3704287780>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:36,100 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f373736b0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f373736b0b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:36,278 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37041ca9e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37041ca9e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:36,353 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37042872e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37042872e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:36,371 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:36,534 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37040c8518>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37040c8518>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:36,609 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37040c8630>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f37040c8630>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:36,634 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f373736b0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f373736b0b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:36,815 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e37ec470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e37ec470>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:36,890 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e37ec1d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e37ec1d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:36,908 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f373736b0b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:36,997 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/losses/semantic_segmentation_losses.py:56: calling softmax_cross_entropy_with_logits_v2_helper (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-10 11:35:37,062 WARNING tensorflow From main_train_and_test_adam_opt.py:140: The name tf.train.AdadeltaOptimizer is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

2019-12-10 11:35:41,038 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1e62860>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:41,117 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1dfac18>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1dfac18>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:41,189 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1dfa390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1dfa390>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:41,207 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:41,360 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1dab1d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1dab1d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:41,433 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1dabc88>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1dabc88>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:41,451 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:41,606 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1dfab38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1dfab38>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:41,678 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1c59c50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1c59c50>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:41,696 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:41,853 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1c37048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1c37048>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:41,925 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1ba0668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1ba0668>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:41,943 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:42,101 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1b4d0b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1b4d0b8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:42,174 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1abf8d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1abf8d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:42,193 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:42,348 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1d94320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1d94320>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:42,424 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1a066d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1a066d8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:42,443 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:42,599 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1a87048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1a87048>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:42,671 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1a87048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1a87048>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:42,696 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:42,871 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e196d518>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e196d518>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:42,944 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e196d588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e196d588>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:42,964 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:43,118 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1971630>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1971630>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:43,189 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1971320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1971320>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:43,215 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:43,388 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e17f3f60>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e17f3f60>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:43,459 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e17f3d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e17f3d68>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:43,477 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:43,630 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1796f28>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e1796f28>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:43,702 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e16a3d68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e16a3d68>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:43,727 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:43,905 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e161a4a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e161a4a8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:43,976 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e161a518>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f36e161a518>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:35:43,994 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f36e1e62860>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:35:44,139 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:44: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

2019-12-10 11:35:44,140 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:47: The name tf.metrics.mean is deprecated. Please use tf.compat.v1.metrics.mean instead.

2019-12-10 11:35:45,073 INFO numexpr.utils NumExpr defaulting to 2 threads.
2019-12-10 11:35:46,136 WARNING tensorflow 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2019-12-10 11:35:46,138 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:48: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2019-12-10 11:35:48,790 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:58: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
2019-12-10 11:35:48,790 WARNING tensorflow `tf.train.start_queue_runners()` was called when no queue runners were defined. You can safely remove the call to this deprecated function.
2019-12-10 11:35:48,792 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:47: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2019-12-10 11:35:49,467 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1282: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-12-10 11:35:49,469 INFO tensorflow Restoring parameters from ./Experiments/SegCaps_multilabels_2019-11-09_01-25-53/weights/model-90000
2019-12-10 11:35:50,404 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:192: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

2019-12-10 11:35:50,404 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:194: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

2019-12-10 11:35:50,404 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:196: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

2019-12-10 11:36:35,565 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:12: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-12-10 11:36:35,565 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-12-10 11:36:35,688 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:18: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-12-10 11:36:35,690 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:19: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

2019-12-10 11:36:35,703 WARNING tensorflow From main_train_and_test_adam_opt.py:101: The name tf.make_template is deprecated. Please use tf.compat.v1.make_template instead.

2019-12-10 11:36:35,705 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/data_generator.py:22: The name tf.FIFOQueue is deprecated. Please use tf.queue.FIFOQueue instead.

2019-12-10 11:36:35,709 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-12-10 11:36:35,710 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/SegCaps.py:27: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
2019-12-10 11:36:35,804 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f31081bed68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f31081bed68>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:35,895 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f310818ea20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f310818ea20>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:35,970 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f31080fc2b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f31080fc2b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:35,989 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f31081beb70>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f31081beb70>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:36,049 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:359: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-10 11:36:36,056 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:389: calling norm (from tensorflow.python.ops.linalg_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-12-10 11:36:36,158 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f31080d30b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f31080d30b8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:36,233 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f310817c160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f310817c160>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:36,252 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:36,416 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed780160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed780160>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:36,490 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed780358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed780358>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:36,509 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:36,671 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed6eb160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed6eb160>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:36,746 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed774c50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed774c50>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:36,765 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:36,926 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed7ef518>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed7ef518>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:37,000 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed7efbe0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed7efbe0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:37,019 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:37,179 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed56a400>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed56a400>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:37,255 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed56a9e8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed56a9e8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:37,273 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:37,439 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed45c198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed45c198>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:37,513 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed638470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed638470>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:37,539 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f3130b900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f3130b900b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:37,717 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed395cc0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed395cc0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:37,791 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed395f28>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed395f28>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:37,810 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:38,082 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed296978>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed296978>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:38,156 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed296668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed296668>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:38,182 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f3130b900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f3130b900b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:38,363 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed1de9b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed1de9b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:38,439 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed3acda0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed3acda0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:38,457 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:38,618 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed0cfd68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed0cfd68>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:38,691 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed0cf6a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed0cf6a0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:38,716 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f3130b900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f3130b900b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:38,893 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed02c518>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed02c518>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:38,967 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed02c630>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30ed02c630>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:38,986 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f3130b900b8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:39,076 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/losses/semantic_segmentation_losses.py:56: calling softmax_cross_entropy_with_logits_v2_helper (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-10 11:36:39,130 WARNING tensorflow From main_train_and_test_adam_opt.py:140: The name tf.train.AdadeltaOptimizer is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

2019-12-10 11:36:43,091 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e76636d8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:43,171 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e75fbc18>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e75fbc18>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:43,246 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e75fb390>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e75fb390>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:43,265 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:43,419 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e75ff550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e75ff550>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:43,491 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e75ffd68>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e75ffd68>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:43,509 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:43,661 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e758b320>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e758b320>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:43,731 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e745c780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e745c780>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:43,749 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:43,902 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e74e9048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e74e9048>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:43,972 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e73fccf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e73fccf8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:43,991 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:44,148 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e7360f98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e7360f98>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:44,220 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e732ddd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e732ddd8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:44,238 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:44,395 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e7293630>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e7293630>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:44,466 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e7273940>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e7273940>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:44,485 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:44,637 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e725ee48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e725ee48>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:44,707 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e7360860>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e7360860>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:44,731 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:44,903 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e716c4a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e716c4a8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:44,973 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e716c630>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e716c630>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:44,992 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:45,150 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e717b198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e717b198>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:45,220 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e717b2b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e717b2b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:45,246 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:45,417 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e71747b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e71747b8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:45,487 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e7174e80>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e7174e80>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:45,506 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:45,658 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e6eda898>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e6eda898>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:45,727 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e6eda588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e6eda588>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:45,752 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:45,921 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e6e0c518>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e6e0c518>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:45,991 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e6eda4a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f30e6eda4a8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:36:46,009 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f30e76636d8>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:36:46,153 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:44: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

2019-12-10 11:36:46,153 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:47: The name tf.metrics.mean is deprecated. Please use tf.compat.v1.metrics.mean instead.

2019-12-10 11:36:46,547 INFO numexpr.utils NumExpr defaulting to 2 threads.
2019-12-10 11:36:46,882 WARNING tensorflow 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2019-12-10 11:36:46,883 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:48: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2019-12-10 11:36:49,468 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:58: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
2019-12-10 11:36:49,468 WARNING tensorflow `tf.train.start_queue_runners()` was called when no queue runners were defined. You can safely remove the call to this deprecated function.
2019-12-10 11:36:49,473 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:47: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2019-12-10 11:36:50,057 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1282: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-12-10 11:36:50,058 INFO tensorflow Restoring parameters from ./Experiments/SegCaps_multilabels_2019-11-09_01-25-53/weights/model-90000
2019-12-10 11:36:50,889 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:192: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

2019-12-10 11:36:50,889 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:194: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

2019-12-10 11:36:50,889 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:196: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

2019-12-10 11:41:24,505 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:12: The name tf.ConfigProto is deprecated. Please use tf.compat.v1.ConfigProto instead.

2019-12-10 11:41:24,506 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:16: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

2019-12-10 11:41:25,649 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:18: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2019-12-10 11:41:25,653 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:19: The name tf.summary.scalar is deprecated. Please use tf.compat.v1.summary.scalar instead.

2019-12-10 11:41:25,666 WARNING tensorflow From main_train_and_test_adam_opt.py:101: The name tf.make_template is deprecated. Please use tf.compat.v1.make_template instead.

2019-12-10 11:41:25,670 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/data_generator.py:22: The name tf.FIFOQueue is deprecated. Please use tf.queue.FIFOQueue instead.

2019-12-10 11:41:25,675 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor
2019-12-10 11:41:25,676 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/SegCaps.py:27: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
2019-12-10 11:41:25,770 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4dd409bda0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4dd409bda0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:25,896 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db81f26d8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db81f26d8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:25,969 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4dd406c4a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4dd406c4a8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:25,989 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:26,052 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:359: calling softmax (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-10 11:41:26,060 WARNING tensorflow From ./Lung_Segmentation/LungSeg/SegCaps/capsule_layers.py:389: calling norm (from tensorflow.python.ops.linalg_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead
2019-12-10 11:41:26,157 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db81b5128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db81b5128>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:26,229 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4dd4059128>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4dd4059128>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:26,245 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:26,407 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4dd408cfd0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4dd408cfd0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:26,482 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4dd408ccf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4dd408ccf8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:26,499 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:26,661 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db07cf160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db07cf160>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:26,734 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db8059e10>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db8059e10>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:26,752 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:26,909 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db0725780>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db0725780>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:26,985 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db07cf358>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db07cf358>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:27,002 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:27,159 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db066f048>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db066f048>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:27,234 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db81b5828>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db81b5828>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:27,252 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:27,414 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db819bc50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db819bc50>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:27,488 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db057e828>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db057e828>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:27,511 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:27,685 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db0491550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db0491550>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:27,758 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db04910f0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db04910f0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:27,774 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:28,027 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db039bc50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db039bc50>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:28,102 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db0491240>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db0491240>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:28,125 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:28,303 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db02c44a8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db02c44a8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:28,376 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db02c49b0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db02c49b0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:28,393 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:28,552 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db01c0b38>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db01c0b38>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:28,626 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db01c0710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db01c0710>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:28,650 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:28,827 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db0105550>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db0105550>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:28,904 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db0105668>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db0105668>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:28,922 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4df94f4198>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:29,010 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/losses/semantic_segmentation_losses.py:56: calling softmax_cross_entropy_with_logits_v2_helper (from tensorflow.python.ops.nn_ops) with dim is deprecated and will be removed in a future version.
Instructions for updating:
dim is deprecated, use axis instead
2019-12-10 11:41:29,080 WARNING tensorflow From main_train_and_test_adam_opt.py:140: The name tf.train.AdadeltaOptimizer is deprecated. Please use tf.compat.v1.train.AdadeltaOptimizer instead.

2019-12-10 11:41:33,085 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d32412470>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:33,163 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d323bac50>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d323bac50>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:33,233 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d323ba3c8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d323ba3c8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:33,250 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:33,402 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d323697b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d323697b8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:33,473 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d323694e0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d323694e0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:33,489 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:33,641 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d32358710>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d32358710>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:33,710 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d32230588>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d32230588>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:33,726 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:33,883 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d323013c8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d323013c8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:33,952 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d32301160>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d32301160>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:33,968 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:34,124 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d32106e48>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d32106e48>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:34,193 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d320da8d0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d320da8d0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:34,210 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:34,365 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db010f198>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4db010f198>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:34,434 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d322a8908>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d322a8908>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:34,450 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:34,604 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d3201eeb8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d3201eeb8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:34,674 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d3201eeb8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d3201eeb8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:34,697 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:34,871 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31f2e470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31f2e470>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:34,942 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d321193c8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d321193c8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:34,959 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:35,112 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31fefdd8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31fefdd8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:35,182 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31fefa20>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31fefa20>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:35,206 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:35,377 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31ffdf98>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31ffdf98>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:35,448 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31ffdcf8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31ffdcf8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:35,464 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:35,620 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31db90b8>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31db90b8>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:35,689 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31c63da0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31c63da0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:35,712 WARNING tensorflow Entity <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method DeconvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.DeconvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:35,884 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31bc4470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31bc4470>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:35,957 WARNING tensorflow Entity <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31bc46a0>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method Conv.call of <tensorflow.python.layers.convolutional.Conv2D object at 0x7f4d31bc46a0>>: AssertionError: Bad argument number for Name: 3, expecting 4
2019-12-10 11:41:35,974 WARNING tensorflow Entity <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>> could not be transformed and will be executed as-is. Please report this to the AutgoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: converting <bound method ConvCapsuleLayer.call of <LungSeg.SegCaps.capsule_layers.ConvCapsuleLayer object at 0x7f4d32412470>>: AttributeError: module 'gast' has no attribute 'Num'
2019-12-10 11:41:36,120 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:44: The name tf.summary.merge is deprecated. Please use tf.compat.v1.summary.merge instead.

2019-12-10 11:41:36,121 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:47: The name tf.metrics.mean is deprecated. Please use tf.compat.v1.metrics.mean instead.

2019-12-10 11:41:36,954 INFO numexpr.utils NumExpr defaulting to 4 threads.
2019-12-10 11:41:37,906 WARNING tensorflow 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

2019-12-10 11:41:37,907 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/utils/summary_handler.py:48: The name tf.summary.FileWriter is deprecated. Please use tf.compat.v1.summary.FileWriter instead.

2019-12-10 11:41:42,803 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:58: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.
Instructions for updating:
To construct input pipelines, use the `tf.data` module.
2019-12-10 11:41:42,803 WARNING tensorflow `tf.train.start_queue_runners()` was called when no queue runners were defined. You can safely remove the call to this deprecated function.
2019-12-10 11:41:42,807 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:47: The name tf.train.Saver is deprecated. Please use tf.compat.v1.train.Saver instead.

2019-12-10 11:41:43,072 WARNING tensorflow From /home/ec2-user/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1282: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
2019-12-10 11:41:43,104 INFO tensorflow Restoring parameters from ./Experiments/SegCaps_multilabels_2019-11-09_01-25-53/weights/model-90000
2019-12-10 11:41:44,383 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:192: The name tf.train.GradientDescentOptimizer is deprecated. Please use tf.compat.v1.train.GradientDescentOptimizer instead.

2019-12-10 11:41:44,383 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:194: The name tf.train.MomentumOptimizer is deprecated. Please use tf.compat.v1.train.MomentumOptimizer instead.

2019-12-10 11:41:44,383 WARNING tensorflow From ./Lung_Segmentation/tensorflow_train/train_loop.py:196: The name tf.train.AdamOptimizer is deprecated. Please use tf.compat.v1.train.AdamOptimizer instead.

